apiVersion: 1

deleteDatasources:
  - name: TimescaleDB
    orgId: 1

datasources:
  - name: TimescaleDB
    type: grafana-postgresql-datasource
    url: timescaledb:5432
    database: ton_metrics
    user: ton
    secureJsonData:
      password: ton_secret
    jsonData:
      database: ton_metrics
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
